#!/bin/bash

if [ "$1" = "serial" ]; then
  node ./serial.js $2 $3 $4
elif [ "$1" = "concurr" ]; then
  node ./concurr.js $2 $3 $4
else
  echo "1st param must be either 'serial' or 'concur'., got '$1'"
  exit
fi
