#!/bin/bash

. ./env/bin/activate

if [ "$1" = "serial" ]; then
  python ./serial.py $2 $3 $4
elif [ "$1" = "concurr" ]; then
  python ./concurr_async.py $2 $3 $4 $5
else
  echo "1st param must be either 'serial' or 'concurr'., got '$1'"
  exit
fi
